
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: sdl2snake
  version: '20.20.09' # just for humans, typically '1.2+git' or '1.3.2'
  summary: a simple snake game writen with C++, and render by SDL2. # 79 char long summary
  description: |
    More detail please view: < https://github.com/Joker2770/SDL2snake >.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots
  base: core18
  
  apps:
    sdl2snake:
      command: bin/SDL2snake
      plugs:
        - opengl
    
  parts:
    sdl2snake:
      after:
        - desktop-glib-only
      # See 'snapcraft plugins'
      plugin: cmake
      source: "https://github.com/Joker2770/SDL2snake.git"
      source-depth: 1
      source-branch: master
      source-type: git
      build-packages:
        - gcc
        - g++
        - cmake
        - make
        - libsdl2-dev
  
      stage-packages:
        - libsdl2-2.0-0
        - libgl1-mesa-glx
        - libglu1-mesa
        
      desktop-glib-only:
        source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-depth: 1
        source-branch: master
        source-type: git
        source-subdir: glib-only
        plugin: make
        build-packages:
          - libglib2.0-dev
        stage-packages:
          - libglib2.0-bin
